#ifdef SPANISH
	#define STR0001 "Informe del Calculo de seguros de salud"
	#define STR0002 "Se imprimira de acuerdo con los parametros solicitados "
	#define STR0003 "por el usuario."
	#define STR0004 "Centro de costo+Matricula"
	#define STR0005 "Empresa: "
	#define STR0006 "Matricula"
	#define STR0007 "Nombre"
	#define STR0008 "¡Informe una fecha de referencia minferior o igual a la Competencia de la planilla de haberes!"
	#define STR0009 "Tipo          Matr/Sec Nombre                         Registro            Tp Proveed         Proveedor                Tp Seguro             Cod Seguro            Val. Empl   Val. Empresa           Total"
	#define STR0010 "Sucursal: "
	#define STR0011 "C.Costo: "
	#define STR0012 "Titular"
	#define STR0013 "Dependiente"
	#define STR0014 "Agregado"
	#define STR0015 "Seguros"
	#define STR0016 "Coparticipacion"
	#define STR0017 "Reembolso"
	#define STR0018 "As. Medica"
	#define STR0019 "As. Odontol."
	#define STR0020 "Rango salarial"
	#define STR0021 "Rango de edad"
	#define STR0022 "Val. Fijo por vida"
	#define STR0023 "% Sobre sueldo"
	#define STR0024 "T O T A L  C E N T R O  D E  C O S T O S"
	#define STR0025 " T O T A L    D E   L A    E M P R E S A       "
	#define STR0026 " T O T A L    D E  L A    S U C U R S A L         "
	#define STR0027 "Competencia: "
	#define STR0028 "Atencion"
	#define STR0029 "Ejecute la opcion del compatibilizador referente al Nuevo Plan de Salud. Para mayores informaciones verifique respectivo Boletin Tecnico."
	#define STR0030 "OK"
	#define STR0031 "Periodo informado no registrado "
	#define STR0032 "Periodo: "
	#define STR0033 "NO EXISTE CENTRO DE COSTO REGISTRADO"
#else
	#ifdef ENGLISH
		#define STR0001 "Health Plan Calculation Report"
		#define STR0002 "It will be printed in accordance with the parameters requested "
		#define STR0003 "by the user."
		#define STR0004 "Cost Center + Registration"
		#define STR0005 "Company: "
		#define STR0006 "Registration"
		#define STR0007 "Name"
		#define STR0008 "Enter a Reference date smaller or equal to Payroll Jurisdiction!"
		#define STR0009 "Type          Registr/Sequ Name                           Entry          Suppl.Type          Supplier               Plan Type              Plan Code             Value Empl   Value Company           Total"
		#define STR0010 "Branch: "
		#define STR0011 "C. Center: "
		#define STR0012 "Sitting Member"
		#define STR0013 "Dependant"
		#define STR0014 "Hired"
		#define STR0015 "Plans"
		#define STR0016 "Co-participation"
		#define STR0017 "Refund"
		#define STR0018 "Medical Assistance"
		#define STR0019 "Dental Assistance"
		#define STR0020 "Salary Range"
		#define STR0021 "Age Range"
		#define STR0022 "Fixed Value per life"
		#define STR0023 "% on salary"
		#define STR0024 "C O S T  C E N T E R  T O T A L"
		#define STR0025 " C O M P A N Y  T O T A L       "
		#define STR0026 " B R A N C H    T O T A L         "
		#define STR0027 "Jurisdiction: "
		#define STR0028 "Attention"
		#define STR0029 "Run the compatibilizer option related to the New Health Plan. For more information, check the respective Technical Newsletter."
		#define STR0030 "OK"
		#define STR0031 "Entered period not registered!"
		#define STR0032 "Period: "
		#define STR0033 "THERE IS NO REGISTERED COST CENTER"
	#else
		#define STR0001 "Relatório do Cálculo de Planos de Saúde"
		#define STR0002 If( cPaisLoc $ "ANG|PTG", "Será impresso de acordo com os parâmetros solicitados ", "Será impresso de acordo com os parametros solicitados " )
		#define STR0003 If( cPaisLoc $ "ANG|PTG", "pelo utilizador.", "pelo usuário." )
		#define STR0004 If( cPaisLoc $ "ANG|PTG", "Centro de Custo+Matrícula", "Centro de Custo+Matricula" )
		#define STR0005 "Empresa: "
		#define STR0006 If( cPaisLoc $ "ANG|PTG", "Matrícula", "Matricula" )
		#define STR0007 "Nome"
		#define STR0008 If( cPaisLoc $ "ANG|PTG", "Informe uma data de referência menor ou igual à competência da folha de pagamento.", "Informe uma data de Referência menor ou igual à Competência da Folha de Pagamento!" )
		#define STR0009 If( cPaisLoc $ "ANG|PTG", "Tipo          Matr/Seq Nome                           Lançamento          Tp.Fornec          Fornecedor               Tp.Plano              Cód.Plano             Vlr. Col.   Vlr. Empresa           Total", "Tipo          Matr/Seq Nome                           Lancamento          Tp Fornec          Fornecedor               Tp Plano              Cod Plano             Vlr. Func   Vlr. Empresa           Total" )
		#define STR0010 "Filial: "
		#define STR0011 "C.Custo: "
		#define STR0012 "Titular"
		#define STR0013 "Dependente"
		#define STR0014 "Agregado"
		#define STR0015 "Planos"
		#define STR0016 "Co-participação"
		#define STR0017 "Reembolso"
		#define STR0018 "Ass. Médica"
		#define STR0019 "Ass. Odontol."
		#define STR0020 "Faixa Salarial"
		#define STR0021 If( cPaisLoc $ "ANG|PTG", "Faixa Etária", "Faixa Etaria" )
		#define STR0022 If( cPaisLoc $ "ANG|PTG", "Vlr.fixo por vida", "Vlr Fixo por vida" )
		#define STR0023 If( cPaisLoc $ "ANG|PTG", "% Sobre salário", "% Sobre salario" )
		#define STR0024 "T O T A L  C E N T R O  D E  C U S T O S"
		#define STR0025 " T O T A L    D A    E M P R E S A       "
		#define STR0026 " T O T A L    D A    F I L I A L         "
		#define STR0027 "Competência: "
		#define STR0028 "Atenção"
		#define STR0029 If( cPaisLoc $ "ANG|PTG", "Execute a opção do compatibilizador referente ao Novo Plano de Saúde. Para mais informação, verifique o respectivo Boletim Técnico.", "Execute a opção do compatibilizador referente ao Novo Plano de Saúde. Para maiores informações, verifique respectivo Boletim Técnico." )
		#define STR0030 "OK"
		#define STR0031 If( cPaisLoc $ "ANG|PTG", "Período informado não registado. ", "Periodo Informado nao Cadastrado! " )
		#define STR0032 If( cPaisLoc $ "ANG|PTG", "Período: ", "Periodo: " )
		#define STR0033 If( cPaisLoc $ "ANG|PTG", "NÃO HÁ CENTRO DE CUSTO REGISTADO", "NAO HA CENTRO DE CUSTO CADASTRADO" )
	#endif
#endif
