#ifdef SPANISH
	#define STR1001 "Centro de costo "
	#define STR1002 "Matricula"
	#define STR1003 "Lista de program. de vacaciones"
	#define STR1004 "Se imprimira de acuerdo con los param. solicitados por el"
	#define STR1005 "usuario."
	#define STR1006 "A rayas"
	#define STR1007 "Administrac."
	#define STR1008 "LISTA DE PROGRAM. DE VACACIONES"
	#define STR1009 "                                                                            FECHA      FCH BASE       P E R I O D O       FCH LIMITE  FCH LIMITE     VACAC.    FALTAS    VACAC.    FALTAS   TOTAL   AGUINALDO   FIRMA DEL   "
	#define STR1010 "SUC   CENTRO COSTO               MAT.     NOMBRE DEL EMPLEADO              INGRESO      VACAC.    A D Q U I S I T I V O     IDEAL       MAXIMA      VENCIDAS  VENCIDAS  PROPORC.  PROPORC.  VACAC.   PORC.	      EMPLEADO   "
	#define STR1011 "LISTA DE PROGRAMACION VACACIONES "
	#define STR1012 "(C. COSTO )"
	#define STR1013 "( MATRICULA )"
	#define STR1014 "  A  "
	#define STR1015 "______/______/______  A  ______/______/______"
	#define STR1016 "Nomb"
	#define STR1017 "C Costo + Nomb"
	#define STR1018 "Sucur + Fch Base"
	#define STR1019 "Sucur + Fch Inicio"
	#define STR1020 "( NOMB )"
	#define STR1021 "(C. COSTO + NOMB )"
	#define STR1022 "( FCH. BASE )"
	#define STR1023 "( FCH. INICIO )"
	#define STR1024 "Seleccionando registros.."
	#define STR1025 "        1ª -  P R O G R .  D E   V A C A C I O N E S "
	#define STR1026 "        2ª -  P R O G R .  D E   V A C A C I O N E S "
	#define STR1027 "        3ª -  P R O G R .  D E   V A C A C I O N E S "
	#define STR1028 "F VAC"
	#define STR1029 "F AUS"
	#define STR1030 "SI "
	#define STR1031 "Fecha           "
	#define STR1032 "Ingreso    "
	#define STR1033 "Fch. Base "
	#define STR1034 "P e r i o d o "
	#define STR1035 "A d q u i s i t. "
	#define STR1036 "Fch Limit"
	#define STR1037 "  Ideal   "
	#define STR1038 " Maxima "
	#define STR1039 "    Vacac. "
	#define STR1040 "Vencidas "
	#define STR1041 "Proporc. "
	#define STR1042 "  Faltas "
	#define STR1043 "    TOTAL"
	#define STR1044 "Aguinal."
	#define STR1045 "Porcent. "
	#define STR1046 "Firma del"
	#define STR1047 "Empleado "
	#define STR1048 "Firma "
	#define STR1049 "Encab. de Vacac."
	#define STR1050 "Emite lista de empleados que tienen programacion de vacaciones previstas"
	#define STR1051 "Lista de Programacion de Receso"
	#define STR1052 "Emite lista de los pasantes que tienen programacion de receso previstas"
	#define STR1053 "                                                                            FECHA       FCH.BASE       P E R I O D O       FCH.LIMITE  FCH.LIMITE    RECESO    RECESO     TOTAL   FIRMA DE "
	#define STR1054 "SUC   CENTRO COSTO               MAT.     NOMBRE                           INGRESO      RECESO      D E   D E R E C H O      IDEAL       MAXIMA      VENCIDO   PROPORC.  RECESO    PASANTE "
	#define STR1055 "  Receso "
	#define STR1056 "Vencido"
	#define STR1057 "         P R O G R A M A C I O N   D E   R E C E S O"
	#define STR1058 "Pasante"
	#define STR1059 "F.REC."
	#define STR1060 "d e   D e r e c h o "
#else
	#ifdef ENGLISH
		#define STR1001 "Cost Center     "
		#define STR1002 "Registration"
		#define STR1003 "Report on Vacation Schedule     "
		#define STR1004 "It will be printed according to parameters selected by the  "
		#define STR1005 "User.   "
		#define STR1006 "Z.Form "
		#define STR1007 "Management   "
		#define STR1008 "REPORT ON VACATION SCHEDULE    "
		#define STR1009 "                                                                           HIRING      VACATION    A C Q U I S I T I V E    IDEAL     MAXIMUM        EXPIRED   EXPIRED   PROPORT.  PROPORT. TOTAL   13thSAL.      EMPLOYEE`S"
		#define STR1010 "BCH   COST CENTER                MAT.     EMPLOYEE`S NAME                  DATE         BASE DT.       P E R I O D          LIMIT DT.   LIMIT DT.   VACATI.   ABSENCES  PERIOD    ABSENC.   VACAT.   PERC.         SIGNATURE"
		#define STR1011 "REPORT ON VACATION SCHEDULE     "
		#define STR1012 "( C.CENTER)"
		#define STR1013 "( REGISTRAT )"
		#define STR1014 " UNT."
		#define STR1015 "______/______/______  TO  ______/______/______"
		#define STR1016 "Name"
		#define STR1017 "C.Center + Name"
		#define STR1018 "Branch + Base Dt."
		#define STR1019 "Branch + Beggin.Dt"
		#define STR1020 "( NAME )"
		#define STR1021 "( COST C. + NAME )"
		#define STR1022 "( BASE DATE )"
		#define STR1023 "( INITIAL DATE )"
		#define STR1024 "Selecting Records...     "
		#define STR1025 "        1st -  V A C A T I O N   S C H E D U L E     "
		#define STR1026 "        2nd -  V A C A T I O N   S C H E D U L E     "
		#define STR1027 "        3rd -  V A C A T I O N   S C H E D U L E     "
		#define STR1028 "D.VAC."
		#define STR1029 "D.OP."
		#define STR1030 "YES"
		#define STR1031 "Date            "
		#define STR1032 "Admission  "
		#define STR1033 "Base Date "
		#define STR1034 "P e r i o d "
		#define STR1035 "A c q u i s i t i v e "
		#define STR1036 "Dt.Limit "
		#define STR1037 "  Best    "
		#define STR1038 "Maximum "
		#define STR1039 "  Vacation "
		#define STR1040 "Overdue  "
		#define STR1041 "Proport. "
		#define STR1042 "Absences "
		#define STR1043 "    TOTAL"
		#define STR1044 "Bonus   "
		#define STR1045 "Percent. "
		#define STR1046 "Employee"
		#define STR1047 "Employee    "
		#define STR1048 "Signature"
		#define STR1049 "Vacations header   "
		#define STR1050 "Issues a list of the employees who have scheduled vacations               "
		#define STR1051 "List of Recess Schedule"
		#define STR1052 "Issues list of interns that have estimated recess schedule."
		#define STR1053 "                                                                            DATE       BASE DT.        P E R I O D           LIMIT DT.   LIMIT DT.    VACATION  ABSENCE   VACATION  ABSENCE  TOTAL   SIGNATURE OF"
		#define STR1054 "BR   COST CENTER               MAT.     NAME                             ADMISSION     RECESS     E N T I T L E D      IDEAL       MAXIMUM      EXPIRED   PROPORT.  VACATION   INTERN"
		#define STR1055 "  Recess "
		#define STR1056 "Due"
		#define STR1057 "         R E C E S S  S C H E D U L E"
		#define STR1058 "Intern"
		#define STR1059 "REC.D."
		#define STR1060 "E n t i t l e d "
	#else
		Static STR1001 := "Centro de Custo "
		Static STR1002 := "Matricula"
		Static STR1003 := "Relacao de Programacao de Ferias."
		Static STR1004 := "Sera impresso de acordo com os parametros solicitados pelo"
		Static STR1005 := "usuario."
		Static STR1006 := "Zebrado"
		Static STR1007 := "Administracao"
		Static STR1008 := "RELACAO DE PROGRAMACAO DE FERIAS"
		Static STR1009 := "                                                                            DATA       DTA.BASE       P E R I O D O       DT.LIMITE   DT.LIMITE      FERIAS    FALTAS    FERIAS    FALTAS   TOTAL   13o SAL.   ASSINATURA DO"
		Static STR1010 := "FIL   CENTRO CUSTO               MAT.     NOME DO FUNCIONARIO              ADMISSAO     FERIAS     A Q U I S I T I V O      IDEAL       MAXIMA      VENCIDAS  VENCIDAS  PROPORC.  PROPORC.  FERIAS   PERC.       FUNCIONARIO"
		Static STR1011 := "RELACAO DE PROGRAMACAO DE FERIAS "
		Static STR1012 := "( C.CUSTO )"
		Static STR1013 := "( MATRICULA )"
		Static STR1014 := "  A  "
		Static STR1015 := "______/______/______  A  ______/______/______"
		#define STR1016  "Nome"
		Static STR1017 := "C.Custo + Nome"
		Static STR1018 := "Filial + Dt.Base"
		Static STR1019 := "Filial + Dt.Inicio"
		Static STR1020 := "( NOME )"
		Static STR1021 := "( C.CUSTO + NOME )"
		Static STR1022 := "( DATA BASE )"
		Static STR1023 := "( DATA INICIO )"
		Static STR1024 := "Selecionando Registros..."
		Static STR1025 := "        1a -  P R O G R A M A C A O  D E  F E R I A S"
		Static STR1026 := "        2a -  P R O G R A M A C A O  D E  F E R I A S"
		Static STR1027 := "        3a -  P R O G R A M A C A O  D E  F E R I A S"
		Static STR1028 := "D.FER."
		Static STR1029 := "D.AB."
		Static STR1030 := "SIM"
		#define STR1031  "Data            "
		#define STR1032  "Admissão   "
		Static STR1033 := "Data Base "
		#define STR1034  "P e r i o d o "
		#define STR1035  "A q u i s i t i v o "
		Static STR1036 := "Dt.Limite"
		Static STR1037 := "  Ideal   "
		Static STR1038 := " Maxima "
		Static STR1039 := "    Ferias "
		#define STR1040  "Vencidas "
		#define STR1041  "Proporc. "
		Static STR1042 := "  Faltas "
		Static STR1043 := "    TOTAL"
		Static STR1044 := "13o Sal."
		#define STR1045  "Percent. "
		#define STR1046  "Assinatura do"
		Static STR1047 := "Funcionario "
		#define STR1048  "Assinatura "
		Static STR1049 := "Cabeçalho de Férias"
		Static STR1050 := "Emite relação dos funcionários que possuem programação de férias previstas"
		#define STR1051  "Relação de Programação de Recesso"
		#define STR1052  "Emite relação dos estagiários que possuem programação de recesso previstas"
		#define STR1053  "                                                                            DATA        DTA.BASE       P E R I O D O       DT.LIMITE   DT.LIMITE     RECESSO   RECESSO    TOTAL   ASSINATURA DO"
		Static STR1054 := "FIL   CENTRO CUSTO               MAT.     NOME                             ADMISSAO     RECESSO     D E   D I R E I T O      IDEAL       MAXIMA      VENCIDO   PROPORC.  RECESSO   ESTAGIARIO"
		#define STR1055  "  Recesso "
		#define STR1056  "Vencido"
		#define STR1057  "         P R O G R A M A Ç Ã O  D E  R E C E S S O"
		#define STR1058  "Estagiário"
		#define STR1059  "D.REC."
		#define STR1060  "d e   D i r e i t o "
	#endif
#endif

#ifndef SPANISH
#ifndef ENGLISH
	STATIC uInit := __InitFun()

	Static Function __InitFun()
	uInit := Nil
	If Type('cPaisLoc') == 'C'

		If cPaisLoc == "ANG"
			STR1001 := "Centro de custo "
			STR1002 := "Registo"
			STR1003 := "Relação De Programação De Férias."
			STR1004 := "Sera impresso de acordo com os parâmetro s solicitados pelo"
			STR1005 := "Utilizador."
			STR1006 := "Código de barras"
			STR1007 := "Administração"
			STR1008 := "Relação De Programação De Férias"
			STR1009 := "                                                                            Data       Dta.base       Período       Dt.limite   Dt.limite      Férias    Faltas    Férias    Faltas   Total   Subsídio De Natal   Assinatura Do"
			STR1010 := "Fil   Centro Custo               Reg.     Nome Do Empregado              Admissão     Férias     Aquisitivo      Ideal       Máxima      Vencidas  Vencidas  Proporç.  Proporç.  Férias   Perc.       Empregado"
			STR1011 := "Relação de programação de férias "
			STR1012 := "( c.custo )"
			STR1013 := "( registo )"
			STR1014 := "  a  "
			STR1015 := "______/______/______  a  ______/______/______"
			STR1017 := "C.custo + Nome"
			STR1018 := "Filial + Dt.base"
			STR1019 := "Filial + Dt.início"
			STR1020 := "( nome )"
			STR1021 := "( c.custo + nome )"
			STR1022 := "( data base )"
			STR1023 := "( data início )"
			STR1024 := "A Seleccionar Registos..."
			STR1025 := "        1a -  P R O G R A M A ç ã O  D E  F é R I A S"
			STR1026 := "        2ª -  Programação De  Férias"
			STR1027 := "        3a -  Programação De Férias"
			STR1028 := "D.fer."
			STR1029 := "D.ab."
			STR1030 := "Sim"
			STR1033 := "Data base "
			STR1036 := "Dt.limite"
			STR1037 := "  ideal   "
			STR1038 := " máxima "
			STR1039 := "    férias "
			STR1042 := "  faltas "
			STR1043 := "    Total"
			STR1044 := "Sub.Natal"
			STR1047 := "Empregado "
			STR1049 := "Cabeçalho De Férias"
			STR1050 := "Emite relação dos empregados que possuem programação de férias previstas"
			STR1054 := "FIL   CENTRO CUSTO               MAT.     NOME                             ADMISSÃO     RECESSO     D E   D I R E I T O      IDEAL       MÁXIMA      VENCIDO   PROPORC.  RECESSO   ESTAGIÁRIO"
		ElseIf cPaisLoc == "PTG"
			STR1001 := "Centro de custo "
			STR1002 := "Registo"
			STR1003 := "Relação De Programação De Férias."
			STR1004 := "Sera impresso de acordo com os parâmetro s solicitados pelo"
			STR1005 := "Utilizador."
			STR1006 := "Código de barras"
			STR1007 := "Administração"
			STR1008 := "Relação De Programação De Férias"
			STR1009 := "                                                                            Data       Dta.base       Período       Dt.limite   Dt.limite      Férias    Faltas    Férias    Faltas   Total   Subsídio De Natal   Assinatura Do"
			STR1010 := "Fil   Centro Custo               Reg.     Nome Do Empregado              Admissão     Férias     Aquisitivo      Ideal       Máxima      Vencidas  Vencidas  Proporç.  Proporç.  Férias   Perc.       Empregado"
			STR1011 := "Relação de programação de férias "
			STR1012 := "( c.custo )"
			STR1013 := "( registo )"
			STR1014 := "  a  "
			STR1015 := "______/______/______  a  ______/______/______"
			STR1017 := "C.custo + Nome"
			STR1018 := "Filial + Dt.base"
			STR1019 := "Filial + Dt.início"
			STR1020 := "( nome )"
			STR1021 := "( c.custo + nome )"
			STR1022 := "( data base )"
			STR1023 := "( data início )"
			STR1024 := "A Seleccionar Registos..."
			STR1025 := "        1a -  P R O G R A M A ç ã O  D E  F é R I A S"
			STR1026 := "        2ª -  Programação De  Férias"
			STR1027 := "        3a -  Programação De Férias"
			STR1028 := "D.fer."
			STR1029 := "D.ab."
			STR1030 := "Sim"
			STR1033 := "Data base "
			STR1036 := "Dt.limite"
			STR1037 := "  ideal   "
			STR1038 := " máxima "
			STR1039 := "    férias "
			STR1042 := "  faltas "
			STR1043 := "    Total"
			STR1044 := "Sub.Natal"
			STR1047 := "Empregado "
			STR1049 := "Cabeçalho De Férias"
			STR1050 := "Emite relação dos empregados que possuem programação de férias previstas"
			STR1054 := "FIL   CENTRO CUSTO               MAT.     NOME                             ADMISSÃO     RECESSO     D E   D I R E I T O      IDEAL       MÁXIMA      VENCIDO   PROPORC.  RECESSO   ESTAGIÁRIO"
		EndIf
		EndIf
	Return Nil
#ENDIF
#ENDIF
