#ifdef SPANISH
	#define STR1001 "Informe de presentacion del cuestionario, sus respuestas y resumen "
	#define STR1002 "conteniendo estadisticas del conjunto de respuestas obtenidas."
	#define STR1003 "Opcion disponible a traves del boton Parametros.   "
	#define STR1004 "A Rayas"
	#define STR1005 "Administracion"
	#define STR1006 "Cuestionario Medico"
	#define STR1007 "Matricula  Nombre Empleado                            Sexo       Admision   Edad"
	#define STR1008 "Preg. Descripc. Pregunta                                         Resp. Fc.Resp.  Cantidad  Complemento"
	#define STR1009 "ANULADO POR EL OPERADOR"
	#define STR1010 "Masculino"
	#define STR1011 "Femenino"
	#define STR1012 "Si"
	#define STR1013 "No"
	#define STR1014 "Resumen del cuestionario - "
	#define STR1015 "Total de empleados analizados:"
	#define STR1016 "Preg. Descripc. Pregunta                                                  Si         No   Sin Respuesta"
	#define STR1017 "¿De Ficha Med.?"
	#define STR1018 "¿A Fich. Medica?"
	#define STR1019 "¿Cliente?"
	#define STR1020 "Tienda"
	#define STR1021 "Codigo del cliente."
	#define STR1022 "Tienda del cliente."
	#define STR1023 "No hay nada para imprimir en el informe."
	#define STR1024 "Cliente/tienda: "
	#define STR1025 "Preg. Descripcion Pregunta                                                                                                                                      Resp. Fch.Resp.  Cantidad Complemento"
	#define STR1026 "Pre.  Descripcion Pregunta                                                                                                                                                                Si        No  Sin Respues."
	#define STR1027 "IDENTIFICACION"
	#define STR1028 "Nombre"
	#define STR1029 "Funcion:"
	#define STR1030 "Centro de Costo"
	#define STR1031 "Edad"
	#define STR1032 "Sexo"
	#define STR1033 "Fecha del Cuestionario"
	#define STR1034 "Fecha Admision"
	#define STR1035 "EXAMEN FISICO"
	#define STR1036 "Senales Vitales"
	#define STR1037 "PA"
	#define STR1038 "Medidas Antopometricas"
	#define STR1039 "Peso"
	#define STR1040 "KG"
	#define STR1041 "Altura"
	#define STR1042 "Tiene alguna deficiencia"
	#define STR1043 "Fisica"
	#define STR1044 "Visual"
	#define STR1045 "Auditiva"
	#define STR1046 "Ninguna"
	#define STR1047 "CUESTIONARIO"
	#define STR1048 "REGISTRO DE LEGITIMIDAD Y VERACIDAD DE LAS INFORMACIONES"
	#define STR1049 "FECHA DE RELLENADO:"
	#define STR1050 "FIRMA DEL COLABORADOR"
	#define STR1051 "FECHA DEK ANALISIS Y EXAMEN"
	#define STR1052 "FIRMA DEL MEDICO EXAMINADOR"
	#define STR1053 "Pag.: "
	#define STR1054 "Fecha "
	#define STR1055 "Hora "
	#define STR1056 "Sin Respuesta"
	#define STR1057 "FIRMA DEL AUXILIAR EN EL RELLENADO / TESTIGO"
	#define STR1058 "¿A Fecha  Realizacion        ?"
	#define STR1059 "¿De Fecha  Realizacion      ?"
	#define STR1060 "¿A Pregunta    ?"
	#define STR1061 "¿De  Pregunta ?"
	#define STR1062 "¿Cuestionario ?"
	#define STR1063 "¿Tipo Impresion?"
	#define STR1064 "Pantalla"
	#define STR1065 "Impresora"
	#define STR1066 "Informe el tipo de impresion. 1=Pantalla o 2=Impresora."
#else
	#ifdef ENGLISH
		#define STR1001 "Presentation report of questionnaire and its answers and summary    "
		#define STR1002 "with statistics of answers from the selectd matter                  "
		#define STR1003 "Option available through the parameter button.   "
		#define STR1004 "Z. Form"
		#define STR1005 "Mangement"
		#define STR1006 "Medical Questionnaire"
		#define STR1007 "Registrat. Name Employee                              Gender     Admission  Age"
		#define STR1008 "Descript.Quest.  Question                                        Ansew Answ.Dt.  Quantity   Complement "
		#define STR1009 "CANCELED by OPERATOR"
		#define STR1010 "Male"
		#define STR1011 "Female"
		#define STR1012 "Yes"
		#define STR1013 "No"
		#define STR1014 "Questionnaire Summary  - "
		#define STR1015 "Total employees or candidates searched:          "
		#define STR1016 "Qust. Quest. Description                                                 Yes        No   No answer. "
		#define STR1017 "From medical card?"
		#define STR1018 "To medical card?  "
		#define STR1019 "Customer ?"
		#define STR1020 "Unit"
		#define STR1021 "Customer code."
		#define STR1022 "Customer unit."
		#define STR1023 "No data to print in the report."
		#define STR1024 "Customer/Unit: "
		#define STR1025 "Quest. Question Description                                                                                                                                    Answ. Answ.Dt.  Complement Amount"
		#define STR1026 "Ques.  Question Description                                                                                                                                                              Yes        No   No Answer"
		#define STR1027 "IDENTIFICATION"
		#define STR1028 "Name"
		#define STR1029 "Function"
		#define STR1030 "Cost Center"
		#define STR1031 "Age"
		#define STR1032 "Gender"
		#define STR1033 "Questionnaire Date"
		#define STR1034 "Admission Date"
		#define STR1035 "Physical Test"
		#define STR1036 "Vital Signs"
		#define STR1037 "PA"
		#define STR1038 "Antopometric Measures"
		#define STR1039 "Weight"
		#define STR1040 "KG"
		#define STR1041 "Height"
		#define STR1042 "Presents any disability"
		#define STR1043 ""
		#define STR1044 "Visual"
		#define STR1045 "Auditive"
		#define STR1046 "None"
		#define STR1047 "QUESTIONNAIRE"
		#define STR1048 "INFORMATION LEGITIMACY AND VERACITY RECORD"
		#define STR1049 "FULFILLMENT DATE"
		#define STR1050 "EMPLOYEE SIGNATURE"
		#define STR1051 "ANALYSIS AND EXAMINATION DATE"
		#define STR1052 "SIGNATURE OF EXAMINER DOCTOR"
		#define STR1053 "PAGE: "
		#define STR1054 "Date: "
		#define STR1055 "Time: "
		#define STR1056 "No Answer"
		#define STR1057 "SIGNATURE OF THE ASSISTANT IN FILLING/WITNESS"
		#define STR1058 "Ate Data Realizacao ?"
		#define STR1059 "De  Data Realizacao ?"
		#define STR1060 "Ate Pergunta ?"
		#define STR1061 "De  Pergunta ?"
		#define STR1062 "Questionario ?"
		#define STR1063 "Tipo Impressão?"
		#define STR1064 "Tela"
		#define STR1065 "Impressora"
		#define STR1066 "Informe o tipo de impressão. 1=Tela ou 2=Impressora."
	#else
		Static STR1001 := "Relatorio de apresentacao do questionario e suas respostas e resumo "
		Static STR1002 := "contento estatistica das respostas do universo selecionado          "
		Static STR1003 := "Opcao disponivel atraves do botao de  parametros.   "
		Static STR1004 := "Zebrado"
		Static STR1005 := "Administracao"
		Static STR1006 := "Questionario Medico"
		Static STR1007 := "Matricula  Nome Funcionario                           Sexo       Admissao   Idade"
		Static STR1008 := "Perg. Descricao Pergunta                                         Resp. Dt.Resp.  Quantidade Complemento"
		Static STR1009 := "CANCELADO PELO OPERADOR"
		#define STR1010  "Masculino"
		#define STR1011  "Feminino"
		#define STR1012  "Sim"
		Static STR1013 := "Nao"
		Static STR1014 := "Resumo do Questionario - "
		Static STR1015 := "Total de Funcionários ou Candidatos Pesquisados.:"
		Static STR1016 := "Per.  Descricao Pergunta                                                  Sim        Nao  Sem Respos."
		Static STR1017 := "De Ficha Médica ?"
		Static STR1018 := "Até Ficha Médica ?"
		Static STR1019 := "Cliente ?"
		#define STR1020  "Loja"
		#define STR1021  "Código do cliente."
		#define STR1022  "Loja do cliente."
		Static STR1023 := "Não há nada para imprimir no relatório."
		Static STR1024 := "Cliente/Loja: "
		Static STR1025 := "Perg. Descricao Pergunta                                                                                                                                      Resp. Dt.Resp.  Quantidade Complemento"
		Static STR1026 := "Per.  Descricao Pergunta                                                                                                                                                                Sim        Nao  Sem Respos."
		#define STR1027  "IDENTIFICAÇÃO"
		#define STR1028  "Nome"
		#define STR1029  "Função"
		#define STR1030  "Centro de Custo"
		#define STR1031  "Idade"
		#define STR1032  "Sexo"
		#define STR1033  "Data do Questionário"
		#define STR1034  "Data Admissão"
		#define STR1035  "EXAME FÍSICO"
		#define STR1036  "Sinais Vitais"
		#define STR1037  "PA"
		#define STR1038  "Medidas Antopométricas"
		#define STR1039  "Peso"
		#define STR1040  "KG"
		#define STR1041  "Altura"
		#define STR1042  "Possui alguma deficiência"
		#define STR1043  "Física"
		#define STR1044  "Visual"
		#define STR1045  "Auditiva"
		#define STR1046  "Nenhuma"
		#define STR1047  "QUESTIONÁRIO"
		Static STR1048 := "REGISTRO DE LEGITIMIDADE E VERACIDADE DAS INFORMAÇÕES"
		#define STR1049  "DATA DO PREENCHIMENTO"
		#define STR1050  "ASSINATURA DO COLABORADOR"
		#define STR1051  "DATA DA ANÁLISE E EXAME"
		#define STR1052  "ASSINATURA DO MÉDICO EXAMINADOR"
		#define STR1053  "Pág.: "
		#define STR1054  "Data: "
		#define STR1055  "Hora: "
		#define STR1056  "Sem Resposta"
		#define STR1057  "ASSINATURA DO AUXILIAR NO REENCHIMENTO/TESTEMUNHA"
		#define STR1058  "Ate Data Realizacao ?"
		#define STR1059  "De  Data Realizacao ?"
		#define STR1060  "Ate Pergunta ?"
		#define STR1061  "De  Pergunta ?"
		#define STR1062  "Questionario ?"
		#define STR1063  "Tipo Impressão?"
		#define STR1064  "Tela"
		#define STR1065  "Impressora"
		#define STR1066  "Informe o tipo de impressão. 1=Tela ou 2=Impressora."
	#endif
#endif

#ifndef SPANISH
#ifndef ENGLISH
	STATIC uInit := __InitFun()

	Static Function __InitFun()
	uInit := Nil
	If Type('cPaisLoc') == 'C'

		If cPaisLoc == "ANG"
			STR1001 := "Relatório de apresentação do questionario e suas respostas e resumo "
			STR1002 := "Contento estatistica das respostas do universo selecionado          "
			STR1003 := "Opção disponivel através do botão de  parâmetro s.   "
			STR1004 := "Código de barras"
			STR1005 := "Administração"
			STR1006 := "Questionário Médico"
			STR1007 := "Matricula  Nome Empregado                           Sexo       Admissão   Idade"
			STR1008 := "Perg. Descrição Pergunta                                         Resp. Dt.resp.  Quantidade Complemento"
			STR1009 := "Cancelado Pelo Operador"
			STR1013 := "Não"
			STR1014 := "Resumo do questionário - "
			STR1015 := "Total de empregados ou candidatos pesquisados.:"
			STR1016 := "Per.  Descrição Pergunta                                                  Sim        Não  Sem Respos."
			STR1017 := "De ficha médica ?"
			STR1018 := "Até ficha médica ?"
			STR1019 := "Cliente?"
			STR1023 := "Não existe informação para imprimir no relatório."
			STR1024 := "Cliente/loja: "
			STR1025 := "Perg. Descrição Pergunta                                                                                                                                      Resp. Dt.Resp.  Quantidade Complemento"
			STR1026 := "Per.  Descrição Pergunta                                                                                                                                                                Sim        Nao  Sem Respos."
			STR1048 := "REGISTO DE LEGITIMIDADE E VERACIDADE DAS INFORMAÇÕES"
		ElseIf cPaisLoc == "PTG"
			STR1001 := "Relatório de apresentação do questionario e suas respostas e resumo "
			STR1002 := "Contento estatistica das respostas do universo selecionado          "
			STR1003 := "Opção disponivel através do botão de  parâmetro s.   "
			STR1004 := "Código de barras"
			STR1005 := "Administração"
			STR1006 := "Questionário Médico"
			STR1007 := "Matricula  Nome Empregado                           Sexo       Admissão   Idade"
			STR1008 := "Perg. Descrição Pergunta                                         Resp. Dt.resp.  Quantidade Complemento"
			STR1009 := "Cancelado Pelo Operador"
			STR1013 := "Não"
			STR1014 := "Resumo do questionário - "
			STR1015 := "Total de empregados ou candidatos pesquisados.:"
			STR1016 := "Per.  Descrição Pergunta                                                  Sim        Não  Sem Respos."
			STR1017 := "De ficha médica ?"
			STR1018 := "Até ficha médica ?"
			STR1019 := "Cliente?"
			STR1023 := "Não existe informação para imprimir no relatório."
			STR1024 := "Cliente/loja: "
			STR1025 := "Perg. Descrição Pergunta                                                                                                                                      Resp. Dt.Resp.  Quantidade Complemento"
			STR1026 := "Per.  Descrição Pergunta                                                                                                                                                                Sim        Nao  Sem Respos."
			STR1048 := "REGISTO DE LEGITIMIDADE E VERACIDADE DAS INFORMAÇÕES"
		EndIf
		EndIf
	Return Nil
#ENDIF
#ENDIF
