#ifdef SPANISH
	#define STR1001 "¿Impresion  Ok?"
	#define STR1002 "MINISTERIO DE HACIENDA"
	#define STR1003 "FISCO DE BRASIL"
	#define STR1004 "Documento de Recaudacion de Ingresos Federales"
	#define STR1005 "DARF"
	#define STR1006 "NOMBRE/TELEFONO"
	#define STR1007 "ATENCION"
	#define STR1008 "   Se prohibe la recaudacion de tributos y contribuciones administrados por la "
	#define STR1009 "Secretaria Federal de Ingresos cuyo valor sea inferior a R$ 10,00. Si ocurre esta"
	#define STR1010 "situacion agregue ese valor al tributo/contribucion del mismo codigo de periodos"
	#define STR1011 "subsecuentes hasta que el total sea igual o superior a R$10,00."
	#define STR1012 "String no utilizada"
	#define STR1013 "PERIODO DE COMPUTO"
	#define STR1014 "NUMERO DE CPF O CGC"
	#define STR1015 "CODIGO DEL INGRESO"
	#define STR1016 "NUMERO DE REFERENCIA"
	#define STR1017 "FCH.DE VENCIMIENTO"
	#define STR1018 "VALOR PRINCIPAL"
	#define STR1019 "VALOR DE MULTA"
	#define STR1020 "VALOR DE INTERES O"
	#define STR1021 "CARGAS DL - 1025/69"
	#define STR1022 "VALOR TOTAL"
	#define STR1023 "AUTENTICACION BANCARIA"
	#define STR1024 "(Solo en las copias 1a y 2a)"
#else
	#ifdef ENGLISH
		#define STR1001 "Is Print Ok?"
		#define STR1002 "MINISTRY OF FINANCE"
		#define STR1003 "BRAZILIAN FEDERAL REVENUE SECRETARIAT"
		#define STR1004 "Federal Revenues Collection Document"
		#define STR1005 "DARF"
		#define STR1006 "NAME/TELEPHONE"
		#define STR1007 "ATTENTION"
		#define STR1008 "   It is prohibited to collect taxes and assessments managed by "
		#define STR1009 "Federal Revenue Secretariat which value is lower than R$ 10,00.In case this "
		#define STR1010 "situation happens add this value to the tax/assessment with the same code of subsequent"
		#define STR1011 "periods until the total is equal or superior to R$10,00."
		#define STR1012 "String not used"
		#define STR1013 "CALCULATION PERIOD"
		#define STR1014 "CPF OU CGC NUMBER"
		#define STR1015 "REVENUE CODE"
		#define STR1016 "REFERENCE NUMBER"
		#define STR1017 "DUE DATE"
		#define STR1018 "MAIN VALUE"
		#define STR1019 "FINE VALUE"
		#define STR1020 "INTERESTS VALUE AND/OR"
		#define STR1021 "DL - 1025/69 CHARGES"
		#define STR1022 "TOTAL VALUE"
		#define STR1023 "BANK AUTHENTICATION"
		#define STR1024 "(Only in 1st and 2nd copies)"
	#else
		Static STR1001 := "Impressäo Ok?"
		Static STR1002 := "MINISTÉRIO DA FAZENDA"
		Static STR1003 := "SECRETARIA DA RECEITA FEDERAL DO BRASIL"
		Static STR1004 := "Documento De Arrecadação De Receitas Federais"
		Static STR1005 := "DARF"
		Static STR1006 := "NOME/TELEFONE"
		Static STR1007 := "ATENÇÃO"
		Static STR1008 := "   É  vedado  o  recolhimento  de  tributos  e  contribuições administrados pela "
		Static STR1009 := "Secretaria da Receita Federal cujo valor seja inferior a R$ 10,00.Ocorrendo tal "
		Static STR1010 := "situação adicione esse valor  ao  tributo/contribuição de mesmo código de períodos"
		Static STR1011 := "subsequentes até que o total seja igual ou superior a R$10,00."
		Static STR1012 := "String nao utilizada"
		Static STR1013 := "PERIODO DE APURAÇÃO"
		Static STR1014 := "NUMERO DO CPF OU CGC"
		Static STR1015 := "CÓDIGO DA RECEITA"
		Static STR1016 := "NÚMERO DE REFERENCIA"
		Static STR1017 := "DATA DE VENCIMENTO"
		Static STR1018 := "VALOR PRINCIPAL"
		Static STR1019 := "VALOR DA MULTA"
		Static STR1020 := "VALOR DOS JUROS E/OU"
		Static STR1021 := "ENCARGOS DL - 1025/69"
		Static STR1022 := "VALOR TOTAL"
		Static STR1023 := "AUTENTICAÇÃO BANCÁRIA"
		Static STR1024 := "(Somente nas 1a e 2a vias)"
	#endif
#endif

#ifndef SPANISH
#ifndef ENGLISH
	STATIC uInit := __InitFun()

	Static Function __InitFun()
	uInit := Nil
	If Type('cPaisLoc') == 'C'

		If cPaisLoc == "ANG"
			STR1001 := "Impressão Ok?"
			STR1002 := "Ministerio da fazenda"
			STR1003 := "Secretaria Da Receita Federal Do Brasil"
			STR1004 := "Documento de arrecadação de receitas federais"
			STR1005 := "Darf"
			STR1006 := "Nome/telefone"
			STR1007 := "Atenção"
			STR1008 := "   e  vedado  o  recolhimento  de  tributos  e  contribuições administrados pela "
			STR1009 := "Secretaria da receita federal cujo valor seja inferior a r$ 10,00.ocorrendo tal "
			STR1010 := "Situação adicione esse valor  ao  tributo/contribuição de mesmo código  de períodos"
			STR1011 := "Subsequentes ate que o total seja igual ou superior a r$10,00."
			STR1012 := "String não utilizada"
			STR1013 := "Período de apuramento"
			STR1014 := "Número Do Cpf Ou Cgc"
			STR1015 := "Código da receita"
			STR1016 := "Nr de referência"
			STR1017 := "Data De Vencimento"
			STR1018 := "Valor Principal"
			STR1019 := "Valor Da Multa"
			STR1020 := "Valor Dos Juros E/ou"
			STR1021 := "Encargos dl - 1025/69"
			STR1022 := "Valor Total"
			STR1023 := "Autenticação bancária"
			STR1024 := "(somente nas 1a e 2a vias)"
		ElseIf cPaisLoc == "PTG"
			STR1001 := "Impressão Ok?"
			STR1002 := "Ministerio da fazenda"
			STR1003 := "Secretaria Da Receita Federal Do Brasil"
			STR1004 := "Documento de arrecadação de receitas federais"
			STR1005 := "Darf"
			STR1006 := "Nome/telefone"
			STR1007 := "Atenção"
			STR1008 := "   e  vedado  o  recolhimento  de  tributos  e  contribuições administrados pela "
			STR1009 := "Secretaria da receita federal cujo valor seja inferior a r$ 10,00.ocorrendo tal "
			STR1010 := "Situação adicione esse valor  ao  tributo/contribuição de mesmo código  de períodos"
			STR1011 := "Subsequentes ate que o total seja igual ou superior a r$10,00."
			STR1012 := "String não utilizada"
			STR1013 := "Período de apuramento"
			STR1014 := "Número Do Cpf Ou Cgc"
			STR1015 := "Código da receita"
			STR1016 := "Nr de referência"
			STR1017 := "Data De Vencimento"
			STR1018 := "Valor Principal"
			STR1019 := "Valor Da Multa"
			STR1020 := "Valor Dos Juros E/ou"
			STR1021 := "Encargos dl - 1025/69"
			STR1022 := "Valor Total"
			STR1023 := "Autenticação bancária"
			STR1024 := "(somente nas 1a e 2a vias)"
		EndIf
		EndIf
	Return Nil
#ENDIF
#ENDIF
